### PR TITLE
Assorted fixes

### PR DESCRIPTION
**Pull request by mattwthompson**
This PR implements all or most of the feedback in issues #6, #7, #8.

- [x] Consistently use `package` over `pkg`
- [x] Add missing `__init__.py` files
- [x] Rename `utils.py` to `utilities.py`
- [x] Remove `pre-commit` configuration
- [x] Fixes a test that was always getting skipped
- [x] Drop `openff-recharge` as a test dependency
- [x] Turn on the unit test for `get_data_file_path`
- [x] Expose `utilities.py` functions at at a higher module level

### CODE REVIEW

**Comment by mattwthompson** [comment]
@simonboothroyd when/if you have some time, could you briefly spot-check these changes?

**Review by SimonBoothroyd — APPROVED** [review]
These look great - thanks @mattwthompson !

**Comment by SimonBoothroyd** [comment]
The one thing you might consider is exposing all of the `utilities.py` utilities in the main `__init__.py` file so you can do

```
from openff.utilities import temporary_cd
```

rather than 

```
from openff.utilities.utilities import temporary_cd
```

**Comment by mattwthompson** [comment]
Seems like a good idea to me

**Comment by mattwthompson** [comment]
Thanks for the feedback and review!

**Pull request merged**
